/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author LABSYS
 */
public class afterstart extends javax.swing.JFrame {

    /**
     * Creates new form afterstart
     */
    public afterstart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        jButton4.setText("Display All");

        jButton5.setText("Display Medical Details");

        jButton6.setText("Display Admission details");

        jLabel4.setText("Please enter Roll no and class and click proceed");

        jLabel5.setText("Roll No");

        jLabel6.setText("Class");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("<--Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jButton1.setText("Display Admission details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 252, 180, 22));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 62, 180, -1));

        jLabel1.setText("Roll No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 39, -1, -1));

        jLabel2.setText("Class");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 65, -1, -1));

        jLabel3.setText("Please enter Roll no and class and click proceed");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 36, 180, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("All");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Medical Details");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Admission Details");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 151, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disha.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rn,c;
        rn=jTextField1.getText();
        c=jTextField2.getText();
        try{Class.forName("java.sql.DriverManager");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/projectmnt","root","1234");
            Statement stmt=(Statement)con.createStatement();
            String query="SELECT * from logindetails,health where logindetails.rollno='"+rn+"'&&logindetails.grade='"+c+"'&&health.rollno='"+rn+"'&&health.grade='"+c+"';";
            ResultSet rs=stmt.executeQuery(query);
            int found=0;
            while(rs.next())
            {String name=rs.getString("name");
                String fathersname=rs.getString("fathersname");
                String mothersname=rs.getString("mothersname");
                String nationality=rs.getString("nationality");
                String dob=rs.getString("dob");
                String mt=rs.getString("mt");
                String fo=rs.getString("fo");
                String mo=rs.getString("mo");
                String residence=rs.getString("residence");
                String city=rs.getString("city");
                String board=rs.getString("board");
                String email=rs.getString("email");
                String state=rs.getString("state");
                String bmi=rs.getString("bmi");
                String height=rs.getString("height");
                String weight=rs.getString("weight");
                String sport=rs.getString("sport");
                String house=rs.getString("house");
 found++;
if(jRadioButton1.isSelected())
{JOptionPane.showMessageDialog(this,"Name: "+name+"\n"+"Fathers Name: "+fathersname+"\n"+"Mothers Name: "+mothersname+"\n"+"Nationality: "+nationality+"\n"+"DOB :"+dob+"\n"+"Mother tongue :"+mt+"\n"+"Mothers Occupation :"+mo+"\n"+"Fathers occupation :"+fo+"\n"+"Residence :"+residence+"\n"+"City :"+city+"\n"+"Board :"+board+"\n"+"Email :"+email+"\n"+"State :"+state+"\n"+"BMI :"+bmi+"\n"+"House :"+house+"\n"+"Sport :"+sport+"\n"+"Weight :"+weight+"\n"+"Height :"+height+"\n");
if(found==0)
 JOptionPane.showMessageDialog(this,"Enter Valid Details");
}          
if(jRadioButton3.isSelected())
                 JOptionPane.showMessageDialog(this,"Name: "+name+"\n"+"Fathers Name: "+fathersname+"\n"+"Mothers Name: "+mothersname+"\n"+"Nationality: "+nationality+"\n"+"DOB :"+dob+"\n"+"Mother tongue :"+mt+"\n"+"Mothers Occupation :"+mo+"\n"+"Fathers occupation :"+fo+"\n"+"Residence :"+residence+"\n"+"City :"+city+"\n"+"Board :"+board+"\n"+"Email :"+email+"\n"+"State :"+state+"\n");
if(jRadioButton2.isSelected())
     JOptionPane.showMessageDialog(this,"BMI :"+bmi+"\n"+"House :"+house+"\n"+"Sport :"+sport+"\n"+"Weight :"+weight+"\n"+"Height :"+height+"\n");
         }
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this,e.getMessage());
        }  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new stuver().setVisible(true);
 dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(afterstart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(afterstart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(afterstart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(afterstart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new afterstart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
